### ISSUE TITLE
Feed contains invalid XML

### ISSUE THREAD

**Issue by rEnr3n** [BlackArch/blackarch-site#67]
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fblackarch.org%2Frss.xml

I can't add the feed to my feed reader. It's whining about feed being invalid.

**Comment by noptrix** [comment]
@Anyon3 ping :)

**Comment by PedroSFreitas** [comment]
> I can't add the feed to my feed reader. It's whining about feed being invalid.

@noptrix and @rEnr3n  I'm gonna **try** to check this tonight.

**Comment by noptrix** [comment]
@rEnr3n this is fixed now. thanks to @PedroSFreitas

**Comment by rEnr3n** [comment]
The link http://ix.io/zn4 is fine but https://blackarch.org/rss.xml is still broken. The official link has not been updated yet.

**Comment by PedroSFreitas** [comment]
@rEnr3n 
I think we have reverted the merge for some reason... It was working.

Edit: it'll be restored soon.

**Comment by PedroSFreitas** [comment]
@rEnr3n restored!
